version: 2
updates:
  - package-ecosystem: "npm" 
    directory: "/" 
    schedule:
      interval: "daily" # Frecuencia: daily, weekly o monthly
    commit-message:
      prefix: "fix" # Prefijo para los commits de Dependabot
    allow:
      - dependency-type: "direct" # Tipos de dependencias a actualizar
