version: 2
updates:
  - package-ecosystem: "npm"  
    directory: "/"  
    schedule:
      interval: "weekly"  
    allow:
      - dependency-type: "direct"  
    commit-message:
      prefix: "fix"  
