version: 2
updates:
  - package-ecosystem: "npm"  
    directory: "/"  # El directorio donde se encuentran los archivos de dependencias
    schedule:
      interval: "weekly"  # Frecuencia para buscar actualizaciones (puede ser "daily", "weekly", "monthly")
    allow:
      - dependency-type: "direct"  # Solo actualizaciones de dependencias directas
    commit-message:
      prefix: "fix"  # Prefijo del mensaje del commit
